version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command: # 수정 필요
      - --config.file=/container/path/prometheus.yml
    volumes: # 수정 필요
      - /local/path/prometheus.yml:/container/prometheus.yml
      # volumes 옵션: .yml 파일(= config 파일) mount 설정
      # left 경로 = vm 내부 경로
      # right 경로 = container 내부 경로
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"