version: '3'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    command: # 수정 필요
      - --config.file=/container/path/prometheus.yml
    volumes: # 수정 필요
      - /local/path/prometheus.yml:/container/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"